app = "krysuk-bot"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "node"

[env]
  NODE_ENV = "production"

[experimental]
  auto_rollback = true

[processes]
  app = "npm start"

[scale]
  count = 1

[checks]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    soft_limit = 0
    hard_limit = 0

  [[services.ports]]
    handlers = []
    port = 0 
